# Generated by Django 5.0.4 on 2024-04-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="weekday",
            field=models.CharField(
                choices=[
                    ("1", "Monday"),
                    ("2", "Tuesday"),
                    ("3", "Wednesday"),
                    ("4", "Thursday"),
                    ("5", "Friday"),
                    ("6", "Saturday"),
                    ("7", "Sunday"),
                ],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
